# There's a chance that this file is rendered
# redundant by configurable Makefile variables
[features]
default = []

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
