/*!
    Definitions relevant to memory management

    This module doesn't implement memory management *per se*, but rather
    expose definitions that assist in implementing it elsewhere, as it
    primarily defines platform-agnostic *advisories*.
*/

/*
    Not quite sure where to put these, so I'll put them here for now...

    Also, what in the Java is this abomination!?
*/

/**
    Platform-agnostic classification of a region in physical memory

    # Background
    This abstraction is primarily inspired by the region classes
    typically found in the PC/BIOS platform, though their presence
    or use isn't strictly limited to that platform.

    # Semantics
    For variants with an `Option<usize>` field, one may use
    `Some(attr)`, where `attr` is the platform-specific
    attributes bit-field. *This is primarily to maintain
    mental compatibility with the PC/BIOS platform, and may
    be generalized to a platform-agnostic contract in the
    near future.*
*/
#[non_exhaustive]
#[derive(Clone, Copy, Debug)]
pub enum PhysMemKind {
    Regular,
    Hole,
    Reclaimable(Option<usize>),
    Reserved(Option<usize>),
    NonVolatile(Option<usize>),
    Other(Option<usize>),
}

/**
    Platform-agnostic classification of a logical memory region

    # Background
    This abstraction is primarily inspired by the region classes
    typically found in the PC/BIOS platform, though their presence
    or use isn't strictly limited to that platform.

    # Semantics
    The internal structure and semantics for this type is currently
    being developed. As such, one should instead provide an alternative
    descriptor type that implements [`MemoryRegionKind`], at least for
    the time being.
*/
// - not quite sure how to use `Mapped` and `Unmapped`, but
//   `SysImg` is certainly useful for preventing self-overwrites
// - should not be used in applications that require more
//   fine-grained bookkeeping (like mature kernels)
// TODO: turn this fella into a state machine of sorts
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LogicalMemKind {
    Mapped,
    Unmapped,
    SysImg,
    Reserved,
    Faulting,
    Other,
}

/**
    Trait that marks a type as a "memory region kind" descriptor
*/
pub trait MemoryRegionKind {
    fn is_usable(&self) -> bool;
    fn is_reclaimable(&self) -> bool;
}

impl MemoryRegionKind for PhysMemKind {
    fn is_usable(&self) -> bool {
        match *self {
            PhysMemKind::Regular => true,
            _ => false,
        }
    }

    fn is_reclaimable(&self) -> bool {
        match *self {
            PhysMemKind::Reclaimable(_) => true,
            _ => false,
        }
    }
}

impl MemoryRegionKind for LogicalMemKind {
    fn is_usable(&self) -> bool {
        *self == LogicalMemKind::Mapped
    }

    fn is_reclaimable(&self) -> bool {
        *self == LogicalMemKind::Unmapped
    }
}

/**
    Platform-agnostic descriptor of a "memory region"

    # Background
    This descriptor aspires to be platform-agnostic, though
    some platform-specific semantics may still be present,
    and should therefore be accounted for in critical
    applications.

    The internal structure, and the semantics, of `MemoryRegion` are
    reminiscent of the memory map layout entries generated by E820h
    in the PC/BIOS platform, though this type is not obligated to
    adhere to ACPI specifications.
*/
#[derive(Clone, Copy, Debug)]
pub struct MemoryRegion<K: MemoryRegionKind> {
    _base: usize,
    _size: usize,
    _kind: K,
}

impl<K: MemoryRegionKind> MemoryRegion<K> {
    /**
        Creates new instance of `MemoryRegion`

        One should not have to run `new()` manually; it should instaed be
        invoked internally by implementors of [`into::<MemoryRegion<K>>()`].

        [`into::<MemoryRegion<K>>()`]: Into::into
    */
    pub const fn new(base: usize, size: usize, kind: K) -> Self {
        MemoryRegion {
            _base: base,
            _size: size,
            _kind: kind,
        }
    }

    /**
        Returns the base address of the region being described
    */
    pub fn base(&self) -> usize {
        self._base
    }

    /**
        Returns the size (in bytes) of the region being described
    */
    pub fn size(&self) -> usize {
        self._size
    }

    /**
        Returns the limit of the region being described

        The returned address is the address of the final
        byte in the region, plus one byte. In other words,
        the address is the theoretical base of a subsequent
        region (or memory hole).

        # Semantics
        If garbage values were provided to [`new()`], such that
        `base() + size()` exceeds [`usize::MAX`], then the
        returned limit will be capped to [`usize::MAX`].

        [`new()`]: Self::new
    */
    pub fn limit(&self) -> usize {
        self._base.saturating_add(self._size)
    }

    /**
        Returns a reference to the memory kind descriptor
    */
    pub fn kind(&self) -> &K {
        &self._kind
    }

    /**
        Returns a mutable reference to the memory kind descriptor
    */
    pub fn kind_mut(&mut self) -> &mut K {
        &mut self._kind
    }

    /**
        Checks whether the described region is usable,
        and returns a truth value
    */
    pub fn is_usable(&self) -> bool {
        self.kind().is_usable()
    }

    /**
        Checks whether the described region is reclaimable,
        and returns a truth value
    */
    pub fn is_reclaimable(&self) -> bool {
        self.kind().is_reclaimable()
    }


    /**
        Checks whether the described region contains the
        provided address, and returns a truth value
    */
    pub fn contains_addr(&self, addr: usize) -> bool {
        self.base() <= addr && addr < self.limit()
    }

    /**
        Checks whether the described region overlaps with the
        provded region, and returns a truth value
    */
    pub fn overlaps(&self, other: &Self) -> bool {
        self.base() < other.limit() && other.base() < self.limit()
    }

    /**
        Checks whether the provided region is fully contained
        within the described region, and returns a truth value
    */
    pub fn contains(&self, other: &Self) -> bool {
        self.base() <= other.base() && other.limit() <= self.limit()
    }

    /**
        Checks whether the described region is fully above the
        provided region, and returns a truth value
    */
    pub fn is_above(&self, other: &Self) -> bool {
        other.limit() <= self.base()
    }

    /**
        Checks whether the described region is fully below the
        provided region, and returns a truth value
    */
    pub fn is_below(&self, other: &Self) -> bool {
        self.limit() <= other.base()
    }
}

/// Type alias for a physical memory region
pub type PhysMemRegion = MemoryRegion<PhysMemKind>;

/// Type alias for a logical memory region
pub type LogicalMemRegion = MemoryRegion<LogicalMemKind>;
